privilee:
  target: dev
  outputs:
    dev:
      type: postgres
      # host: localhost
      host: host.docker.internal
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      port: 5432  # Default to 5432 if not set
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: "{{ env_var('POSTGRES_SCHEMA') }}"
      threads: 2