SELECT
    date(EVENT_TIMESTAMP_LTZ) AS USAGE_DATE,
    FK_VENUE_ID,
    count(DISTINCT FK_USER_ID) AS UNIQUE_CHECKINS_COUNT,
    count(FK_USER_ID) AS TOTAL_CHECKINS_COUNT

FROM {{ ref('stage_venue_register') }}
WHERE EVENT_NAME = 'ENTER'
GROUP BY 1, 2
