name: 'privilee'
version: '1.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'privilee'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["models"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"


models:
  +on_schema_change: "sync_all_columns"
  +copy_grants: true
  +persist_docs:
    relation: true
    columns: true
  privilee:
    seeds:
      +schema: dl_capacity_data
      +persist_docs:
        relation: true
        columns: true
    models:
      stage:
        +schema: stage_capacity_data
        +materialized: table
        +persist_docs:
          relation: true
          columns: true
